<?php
/**
 * @file
 * Code for the OpenSanMateo Rotator feature.
 */

include_once 'opensanmateo_rotator.features.inc';

/**
 * Implements hook_entity_info_alter()
 *
 * Defines a new bundle type for the rotator pane
 */
function opensanmateo_rotator_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['custom_content_pane'] = $entity_info['fieldable_panels_pane']['bundles']['fieldable_panels_pane'];
  $entity_info['fieldable_panels_pane']['bundles']['custom_content_pane']['label'] = 'Content Pane';
  $entity_info['fieldable_panels_pane']['bundles']['custom_content_pane']['admin']['path'] = 'admin/structure/fieldable-panels-panes/manage/%custom_content_panes_type';
  $entity_info['fieldable_panels_pane']['bundles']['custom_content_pane']['admin']['real path'] = 'admin/structure/fieldable-panels-panes/manage/custom-content-pane';

  $entity_info['fieldable_panels_pane']['bundles']['rotator_panels_pane'] = $entity_info['fieldable_panels_pane']['bundles']['fieldable_panels_pane'];
  $entity_info['fieldable_panels_pane']['bundles']['rotator_panels_pane']['label'] = 'Rotator Pane';
  $entity_info['fieldable_panels_pane']['bundles']['rotator_panels_pane']['admin']['path'] = 'admin/structure/fieldable-panels-panes/manage/%rotator_panels_panes_type';
  $entity_info['fieldable_panels_pane']['bundles']['rotator_panels_pane']['admin']['real path'] = 'admin/structure/fieldable-panels-panes/manage/rotator-panels-pane';

  $entity_info['fieldable_panels_pane']['bundles']['promo_panels_pane'] = $entity_info['fieldable_panels_pane']['bundles']['fieldable_panels_pane'];
  $entity_info['fieldable_panels_pane']['bundles']['promo_panels_pane']['label'] = 'Promo Pane';
  $entity_info['fieldable_panels_pane']['bundles']['promo_panels_pane']['admin']['path'] = 'admin/structure/fieldable-panels-panes/manage/%promo_panels_panes_type';
  $entity_info['fieldable_panels_pane']['bundles']['promo_panels_pane']['admin']['real path'] = 'admin/structure/fieldable-panels-panes/manage/promo-panels-pane';
}

/**
 * Implementation of template_preprocess_field().
 */
function opensanmateo_rotator_preprocess_field(&$vars, $hook) {
  if ($vars['element']['#field_name'] != 'field_coll_rotator_item') {
    return;
  }

  foreach ($vars['element']['#items'] as $index => $item) {
    $value = $item['value'];
    $slide = $vars['items'][$index]['entity']['field_collection_item'][$value];
    $link = NULL;

    // give a value for the entity id visible in $items
    $vars['items'][$index]['#eid'] = $value;

    // wrap the caption in an h3
    if (isset($slide['field_rotator_caption'])) {
      $slide['field_rotator_caption'][0]['#markup'] = '<h3>' . $slide['field_rotator_caption'][0]['#markup'] . '</h3>';
    }
    // Move description into the caption
    if (isset($slide['field_rotator_description']) && isset($slide['field_rotator_caption'])) {
      $slide['field_rotator_caption'][0]['#markup'] .= '<p>' . $slide['field_rotator_description'][0]['#markup'] . '</p>';
      unset($slide['field_rotator_description']);
      $vars['items'][$index]['entity']['field_collection_item'][$value] = $slide;
    }

    // Fetch link
    if (isset($slide['field_rotator_link_url'])) {
      $link = $slide['field_rotator_link_url']['#items'][0]['url'];
    }
    if (isset($slide['field_rotator_link_node'])) {
      if (isset($slide['field_rotator_link_node'][0]['#markup'])) {
        $link = $slide['field_rotator_link_node'][0]['#markup'];
      }
      else {
        $link = $slide['field_rotator_link_node'][0]['#href'];
      }
    }
    // give a value for the entity id visible in $items
    $vars['items'][$index]['#eid'] = $value;

    if (!empty($link)) {
      // this seems like semi-cheating - but there doesn't seem to be a more drupally way to do this
      $l = l('|', $link, array('attributes' => array('class' => array('rotator-wrap-link'))));
      $parts = explode('|', $l);

      // wrap the image in our link
      $vars['items'][$index]['entity']['field_collection_item'][$value]['field_rotator_image']['#prefix'] = $parts[0];
      $vars['items'][$index]['entity']['field_collection_item'][$value]['field_rotator_image']['#suffix'] = $parts[1];

      // hide the links
      hide($vars['items'][$index]['entity']['field_collection_item'][$value]['field_rotator_link_url']);
      hide($vars['items'][$index]['entity']['field_collection_item'][$value]['field_rotator_link_node']);
    }
  }
}

/**
 * Implements template_preprocess_panels_pane().
 */
function opensanmateo_rotator_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type == 'fieldable_panels_pane' && isset($vars['content']['field_coll_rotator_item']['#bundle']) &&
      $vars['content']['field_coll_rotator_item']['#bundle'] == 'rotator_panels_pane') {

    // Determine the type (Carousel or rotator)
    $type = field_get_items('fieldable_panels_pane', $vars['content']['field_coll_rotator_item']['#object'], 'field_rotator_type');
    if ($type) {
      $type = reset($type);
      $type = $type['value'];
    }
    else {
      $type = 'none';
    }

    $advance = field_get_items('fieldable_panels_pane', $vars['content']['field_coll_rotator_item']['#object'], 'field_auto_advance');
    if ($advance) {
      $advance = reset($advance);
      $advance = $advance['value'];
    }
    else {
      $advance = 0;
    }
    
    $advanceSpeed = field_get_items('fieldable_panels_pane', $vars['content']['field_coll_rotator_item']['#object'], 'field_auto_advance_speed');
    if ($advanceSpeed) {
      $advanceSpeed = reset($advanceSpeed);
      $advanceSpeed = $advanceSpeed['value'];
    }
    else {
      $advanceSpeed = 5000;
    }

    $fpid = $vars['content']['field_coll_rotator_item']['#object']->fpid;

    drupal_add_js(array('OpenSanMateoRotator' => array(array('type' => $type, 'fpid' => $fpid, 'advance' => $advance, 'advanceSpeed' => $advanceSpeed))), 'setting');

    if ($type != 'list') {
      flexslider_add();
      drupal_add_css(drupal_get_path('module', 'opensanmateo_rotator') . '/opensanmateo_rotator.css');
      drupal_add_js(drupal_get_path('module', 'opensanmateo_rotator') . '/opensanmateo_rotator.js');
    }

  }

  // if we have a promo pane we need to pull out the url and use it on the image and the link
  // must check to see if it isset first as some panes have pre-rendered HTML for $vars['content']
  if (isset($vars['content']['#bundle']) && $vars['content']['#bundle'] == 'promo_panels_pane') {
    $url = '';
    $url = isset($vars['content']['field_rotator_link_url'][0]['#element']['url']) ? $vars['content']['field_rotator_link_url'][0]['#element']['url'] : $url;
    $url = isset($vars['content']['field_rotator_link_node'][0]['#markup']) ? $vars['content']['field_rotator_link_node'][0]['#markup'] : $url;
    unset($vars['content']['field_rotator_link_node']);
    if($url) {
      $url = trim($url, "/");
      $vars['content']['field_rotator_link_url'][0]['#element']['url'] = $url;
      $vars['content']['field_rotator_image'][0]['#path']['path'] = $url;
    }
  }
}
