<?php
/**
 * @file
 * Code for the OpenSanMateo Frontend feature.
 */

include_once 'opensanmateo_frontend.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function opensanmateo_frontend_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'sanmateo-primary-menu' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Dropdown Menu - Menu Block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 2,
      'expanded'    => 1,
      'sort'        => 0,
    ),
  );
}

function opensanmateo_frontend_menu_alter(&$items) {
  //dsm($items);
}