<?php
/**
 * @file
 * Code for the OpenSanMateo Frontend feature.
 */

include_once 'opensanmateo_frontend.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function opensanmateo_frontend_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'sanmateo-primary-menu' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Dropdown Menu - Menu Block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 2,
      'expanded'    => 1,
      'sort'        => 0,
    ),
    'subnav-menu' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Sub-nav menu block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 1,
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function opensanmateo_frontend_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'layouts') {
    return 'plugins/layouts';
  }
}