<?php
/**
 * @file
 * Contains the install/uninstall hooks for the module
 */


/**
 * Enable HTTPS for all authenticated traffic. Forces anonymous traffic to HTTP.
 */
function opensanmateo_security_update_7001() {
  variable_set('securepages_roles', array(
    2 => '2',
    3 => 0,
    4 => 0,
    6 => 0,
    5 => 0,
    7 => 0,
  ));

  variable_set('securepages_switch', TRUE);

  return array();
}
