<?php
/**
 * @file
 * Code for the OpenSanMateo Location feature.
 */

include_once 'opensanmateo_location.features.inc';
include_once 'opensanmateo_location.location_address.inc';

/**
 * implements hook_features_template_info()
 */
function opensanmateo_location_features_template_info() {
  $content_types = variable_get('opensanmateo_location_content_types_with_location', array());
  $data = array();
  foreach($content_types as $content_type => $present) {
    $data[] = array(
      'entity_type' => 'node',
      'bundle_type' => $content_type,
      'field' => 'field_location_address',
      'plugin' => 'field_instance',
      'deleted' => !$present,
      'template' => 'open_sanmateo_location_field_default_field_instances_template'
    );
  }
  return $data;
}

/**
 * implements hook_field_widget_form_alter(&$element, &$form_state, $context)
 */
function opensanmateo_location_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['#field_name'])  && ($element['#field_name']  == 'field_location_address')) {
    $element['#attached']['js'][] = drupal_get_path("module", "opensanmateo_location") . "/opensanmateo_location.js";
  }
}

/**
 * implements hook_menu()
 *
 * we are adding a menu callback for our ajax call to look up an address
 *
 * @see opensanmateo_location.js
 */
function opensanmateo_location_menu() {
  $items['opensanmateo_location/ajax/%'] = array(
    'page callback' => 'opensanmateo_location_address_lookup',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'access arguments' => array(2, 3, 4),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * menu call back that find the address from a search reference
 */
function opensanmateo_location_address_lookup($location) {
  $id = search_api_reference_extract_key($location);
  $view = views_get_view('opensanmateo_search');
  $view->set_display('block_2');
  $view->set_arguments(array($id));
  $view->pre_execute();
  $view->execute();
  foreach($view->result as $result) {
    $item = $result->_entity_properties;
    $rtn[] = array(
      'state' => $item['search_api_aggregation_4'],
      'zip' => $item['search_api_aggregation_5'],
      'street' => $item['search_api_aggregation_6'],
      'city' => $item['search_api_aggregation_7'],
    );
  }
  $address = isset($rtn[0]) ? $rtn[0] : stdClass();
  drupal_json_output($address);
}

/**
 * Implements hook_permission().
 * 
 * Defines the 'edit quick search tags' permission
 */
function opensanmateo_location_permission() {
  return array(
    'edit quick search tags' => array(
      'title' => t('Edit Quick Search Tags'),
      'description' => t('Edit Quick Search tags on the Location content type.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 * 
 * Disables the Quick Search tags field if the permission isn't set.
 */
function opensanmateo_location_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($form['field_quick_search'])) {
    return;
  }
  if (!user_access('edit quick search tags')) {
    $form['field_quick_search']['#disabled'] = TRUE;
  }
}
