<?php
/**
 * @file
 * OpenSanMateo .module file.
 */

/**
 * Implements hook_node_presave();
 */
function opensanmateo_webform_captcha_node_presave($node) {
  if (in_array($node->type, variable_get('webform_node_types', array('webform')))) {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $enabled = $node_wrapper->field_captcha->value();
    if ($enabled) {
      // CAPTCHA has been enabled for this Webform.
      // We need the form_id of the Webform; not the node.
      // Webform builds the ID as: 'webform_client_form_' . $node->nid.
      $form_id = 'webform_client_form_' . $node->nid;
      // Check to see if CAPTCHA is enabled for this $form_id. To do this we
      // need to load the CAPTCHA inc file to get to the proper method.
      module_load_include('inc', 'captcha');
      // Get CAPTCHA type and module for given form_id.
      $captcha_point = captcha_get_form_id_setting($form_id);
      if (!$captcha_point || $captcha_point->captcha_type === NULL) {
        // Enable CAPTCHA for this node.
        captcha_set_form_id_setting($form_id, 'default');
      }
    }
    // TODO: handle disabling captcha.
  }
}